<a href="https://colab.research.google.com/github/lintabong/ATapp/blob/master/python-math/attemp0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy
import sympy

In [ ]:
x = sympy.symbols('x')
E = 10
I = 2
L = 3
k_x = 2 + x

In [180]:
def result(e, i, l, K_x):
  x = sympy.symbols('x')
  N1 = 1 - 3*(x**2)/(l**2) + 2*(x**3)/(l**3)
  N2 = x - 2*(x**2)/l + (x**3)/(l**2)
  N3 = 3*(x**2)/(l**2) - 2*(x**3)/(l**3)
  N4 = -(x**2)/l + (x**3)/(l**2)
  N  = numpy.matrix([N1, N2, N3, N4])

  B1 = -6/(l**2) + 12*x/(l**3)
  B2 = -4/l + 6*x/(l**2)
  B3 = 6/(l**2) - 12*x/(l**3)
  B4 = -2/l + 6*x/(l**2)
  B = numpy.matrix([B1, B2, B3, B4])

  kb = numpy.transpose(B)*e*i*B
  kn = numpy.transpose(N)*N

  for j in range(4):
    for k in range(4):
      kn[j,k] = kn[j,k]*K_x

  for j in range(4):
    for k in range(4):
      kb[j,k] = sympy.integrate(kb[j,k], (x,0,L))
      kn[j,k] = sympy.integrate(kn[j,k], (x,0,L))
      
  return kb + kn

In [179]:
x = sympy.symbols('x')
y = result(10,2,3,2+x)

print(y)

[[11.8888888888889 14.7261904761905 -7.53888888888889 12.3904761904762]
 [14.7261904761905 27.4702380952381 -12.3261904761905 12.6583333333334]
 [-7.53888888888889 -12.3261904761905 13.6888888888889 -15.2404761904762]
 [12.3904761904762 12.6583333333334 -15.2404761904762 27.6630952380953]]
